//! Unit definitions for config-level scaling.
//!
//! This module provides enums and helpers for working with physical units
//! (length and mass) using `uom`. Intended for use in configuration and
//! scaling of simulation parameters.

use uom::si::{
    f64::{Length, Mass},
    length::{
        angstrom, astronomical_unit, atomic_unit_of_length, attometer, bohr_radius, centimeter,
        chain, decameter, decimeter, exameter, fathom, femtometer, fermi, foot, foot_survey,
        gigameter, hectometer, inch, kilometer, light_year, megameter, meter, microinch,
        micrometer, micron, mil, mile, mile_survey, millimeter, nanometer, nautical_mile, parsec,
        petameter, pica_computer, pica_printers, picometer, point_computer, point_printers, rod,
        terameter, yard, yoctometer, yottameter, zeptometer, zettameter,
    },
    mass::{
        attogram, carat, centigram, dalton, decagram, decigram, exagram, femtogram, gigagram,
        grain, gram, hectogram, hundredweight_long, hundredweight_short, kilogram, megagram,
        microgram, milligram, nanogram, ounce, ounce_troy, pennyweight, petagram, picogram, pound,
        pound_troy, slug, teragram, ton, ton_assay, ton_long, ton_short, yoctogram, yottagram,
        zeptogram, zettagram,
    },
};

#[derive(Clone, Copy)]
#[allow(dead_code)]
pub enum LengthUnit {
    Angstrom,
    AstronomicalUnit,
    AtomicUnitOfLength,
    Attometer,
    BohrRadius,
    Centimeter,
    Chain,
    Decameter,
    Decimeter,
    Exameter,
    Fathom,
    Femtometer,
    Fermi,
    Foot,
    FootSurvey,
    Gigameter,
    Hectometer,
    Inch,
    Kilometer,
    LightYear,
    Megameter,
    Meter,
    Microinch,
    Micrometer,
    Micron,
    Mil,
    Mile,
    MileSurvey,
    Millimeter,
    Nanometer,
    NauticalMile,
    Parsec,
    Petameter,
    PicaComputer,
    PicaPrinters,
    Picometer,
    PointComputer,
    PointPrinters,
    Rod,
    Terameter,
    Yard,
    Yoctometer,
    Yottameter,
    Zeptometer,
    Zettameter,
}

impl LengthUnit {
    /// Gets the length value f64 in terms of the self-unit
    pub fn get(&self, length: Length) -> f64 {
        match self {
            LengthUnit::Angstrom => length.get::<angstrom>(),
            LengthUnit::AstronomicalUnit => length.get::<astronomical_unit>(),
            LengthUnit::AtomicUnitOfLength => length.get::<atomic_unit_of_length>(),
            LengthUnit::Attometer => length.get::<attometer>(),
            LengthUnit::BohrRadius => length.get::<bohr_radius>(),
            LengthUnit::Centimeter => length.get::<centimeter>(),
            LengthUnit::Chain => length.get::<chain>(),
            LengthUnit::Decameter => length.get::<decameter>(),
            LengthUnit::Decimeter => length.get::<decimeter>(),
            LengthUnit::Exameter => length.get::<exameter>(),
            LengthUnit::Fathom => length.get::<fathom>(),
            LengthUnit::Femtometer => length.get::<femtometer>(),
            LengthUnit::Fermi => length.get::<fermi>(),
            LengthUnit::Foot => length.get::<foot>(),
            LengthUnit::FootSurvey => length.get::<foot_survey>(),
            LengthUnit::Gigameter => length.get::<gigameter>(),
            LengthUnit::Hectometer => length.get::<hectometer>(),
            LengthUnit::Inch => length.get::<inch>(),
            LengthUnit::Kilometer => length.get::<kilometer>(),
            LengthUnit::LightYear => length.get::<light_year>(),
            LengthUnit::Megameter => length.get::<megameter>(),
            LengthUnit::Meter => length.get::<meter>(),
            LengthUnit::Microinch => length.get::<microinch>(),
            LengthUnit::Micrometer => length.get::<micrometer>(),
            LengthUnit::Micron => length.get::<micron>(),
            LengthUnit::Mil => length.get::<mil>(),
            LengthUnit::Mile => length.get::<mile>(),
            LengthUnit::MileSurvey => length.get::<mile_survey>(),
            LengthUnit::Millimeter => length.get::<millimeter>(),
            LengthUnit::Nanometer => length.get::<nanometer>(),
            LengthUnit::NauticalMile => length.get::<nautical_mile>(),
            LengthUnit::Parsec => length.get::<parsec>(),
            LengthUnit::Petameter => length.get::<petameter>(),
            LengthUnit::PicaComputer => length.get::<pica_computer>(),
            LengthUnit::PicaPrinters => length.get::<pica_printers>(),
            LengthUnit::Picometer => length.get::<picometer>(),
            LengthUnit::PointComputer => length.get::<point_computer>(),
            LengthUnit::PointPrinters => length.get::<point_printers>(),
            LengthUnit::Rod => length.get::<rod>(),
            LengthUnit::Terameter => length.get::<terameter>(),
            LengthUnit::Yard => length.get::<yard>(),
            LengthUnit::Yoctometer => length.get::<yoctometer>(),
            LengthUnit::Yottameter => length.get::<yottameter>(),
            LengthUnit::Zeptometer => length.get::<zeptometer>(),
            LengthUnit::Zettameter => length.get::<zettameter>(),
        }
    }
}

#[derive(Clone, Copy)]
#[allow(dead_code)]
pub enum MassUnit {
    Attogram,
    Femtogram,
    Picogram,
    Nanogram,
    Microgram,
    Milligram,
    Centigram,
    Decigram,
    Gram,
    Decagram,
    Hectogram,
    Kilogram,
    Megagram,
    Gigagram,
    Teragram,
    Petagram,
    Exagram,
    Zettagram,
    Yottagram,
    Yoctogram,
    Zeptogram,
    Dalton,
    Carat,
    Grain,
    HundredweightLong,
    HundredweightShort,
    Ton,
    TonAssay,
    TonLong,
    TonShort,
    Ounce,
    OunceTroy,
    Pennyweight,
    Pound,
    PoundTroy,
    Slug,
}

impl MassUnit {
    /// Gets the mass value f64 in terms of the self-unit
    pub fn get(&self, mass: Mass) -> f64 {
        match self {
            MassUnit::Attogram => mass.get::<attogram>(),
            MassUnit::Femtogram => mass.get::<femtogram>(),
            MassUnit::Picogram => mass.get::<picogram>(),
            MassUnit::Nanogram => mass.get::<nanogram>(),
            MassUnit::Microgram => mass.get::<microgram>(),
            MassUnit::Milligram => mass.get::<milligram>(),
            MassUnit::Centigram => mass.get::<centigram>(),
            MassUnit::Decigram => mass.get::<decigram>(),
            MassUnit::Gram => mass.get::<gram>(),
            MassUnit::Decagram => mass.get::<decagram>(),
            MassUnit::Hectogram => mass.get::<hectogram>(),
            MassUnit::Kilogram => mass.get::<kilogram>(),
            MassUnit::Megagram => mass.get::<megagram>(),
            MassUnit::Gigagram => mass.get::<gigagram>(),
            MassUnit::Teragram => mass.get::<teragram>(),
            MassUnit::Petagram => mass.get::<petagram>(),
            MassUnit::Exagram => mass.get::<exagram>(),
            MassUnit::Zettagram => mass.get::<zettagram>(),
            MassUnit::Yottagram => mass.get::<yottagram>(),
            MassUnit::Yoctogram => mass.get::<yoctogram>(),
            MassUnit::Zeptogram => mass.get::<zeptogram>(),
            MassUnit::Dalton => mass.get::<dalton>(),
            MassUnit::Carat => mass.get::<carat>(),
            MassUnit::Grain => mass.get::<grain>(),
            MassUnit::HundredweightLong => mass.get::<hundredweight_long>(),
            MassUnit::HundredweightShort => mass.get::<hundredweight_short>(),
            MassUnit::Ton => mass.get::<ton>(),
            MassUnit::TonAssay => mass.get::<ton_assay>(),
            MassUnit::TonLong => mass.get::<ton_long>(),
            MassUnit::TonShort => mass.get::<ton_short>(),
            MassUnit::Ounce => mass.get::<ounce>(),
            MassUnit::OunceTroy => mass.get::<ounce_troy>(),
            MassUnit::Pennyweight => mass.get::<pennyweight>(),
            MassUnit::Pound => mass.get::<pound>(),
            MassUnit::PoundTroy => mass.get::<pound_troy>(),
            MassUnit::Slug => mass.get::<slug>(),
        }
    }
}
