//! Unit definitions for config-level scaling.
//!
//! This module provides enums and helpers for working with physical units
//! (length and mass) using `uom`. Intended for use in configuration and
//! scaling of simulation parameters.

use uom::si::{
    f32::{Length, Mass},
    length::{
        angstrom, astronomical_unit, atomic_unit_of_length, attometer, bohr_radius, centimeter,
        chain, decameter, decimeter, exameter, fathom, femtometer, fermi, foot, foot_survey,
        gigameter, hectometer, inch, kilometer, light_year, megameter, meter, microinch,
        micrometer, micron, mil, mile, mile_survey, millimeter, nanometer, nautical_mile, parsec,
        petameter, pica_computer, pica_printers, picometer, point_computer, point_printers, rod,
        terameter, yard, yoctometer, yottameter, zeptometer, zettameter,
    },
    mass::{
        attogram, carat, centigram, dalton, decagram, decigram, exagram, femtogram, gigagram,
        grain, gram, hectogram, hundredweight_long, hundredweight_short, kilogram, megagram,
        microgram, milligram, nanogram, ounce, ounce_troy, pennyweight, petagram, picogram, pound,
        pound_troy, slug, stone, teragram, ton, ton_assay, ton_long, ton_short, tonne, yoctogram,
        yottagram, zeptogram, zettagram,
    },
};

#[derive(Clone, Copy)]
enum LengthUnit {
    Angstrom,
    AstronomicalUnit,
    AtomicUnitOfLength,
    Attometer,
    BohrRadius,
    Centimeter,
    Chain,
    Decameter,
    Decimeter,
    Exameter,
    Fathom,
    Femtometer,
    Fermi,
    Foot,
    FootSurvey,
    Gigameter,
    Hectometer,
    Inch,
    Kilometer,
    LightYear,
    Megameter,
    Meter,
    Microinch,
    Micrometer,
    Micron,
    Mil,
    Mile,
    MileSurvey,
    Millimeter,
    Nanometer,
    NauticalMile,
    Parsec,
    Petameter,
    PicaComputer,
    PicaPrinters,
    Picometer,
    PointComputer,
    PointPrinters,
    Rod,
    Terameter,
    Yard,
    Yoctometer,
    Yottameter,
    Zeptometer,
    Zettameter,
}

impl LengthUnit {
    fn create(&self, value: f32) -> Length {
        match self {
            LengthUnit::Angstrom => Length::new::<angstrom>(value),
            LengthUnit::AstronomicalUnit => Length::new::<astronomical_unit>(value),
            LengthUnit::AtomicUnitOfLength => Length::new::<atomic_unit_of_length>(value),
            LengthUnit::Attometer => Length::new::<attometer>(value),
            LengthUnit::BohrRadius => Length::new::<bohr_radius>(value),
            LengthUnit::Centimeter => Length::new::<centimeter>(value),
            LengthUnit::Chain => Length::new::<chain>(value),
            LengthUnit::Decameter => Length::new::<decameter>(value),
            LengthUnit::Decimeter => Length::new::<decimeter>(value),
            LengthUnit::Exameter => Length::new::<exameter>(value),
            LengthUnit::Fathom => Length::new::<fathom>(value),
            LengthUnit::Femtometer => Length::new::<femtometer>(value),
            LengthUnit::Fermi => Length::new::<fermi>(value),
            LengthUnit::Foot => Length::new::<foot>(value),
            LengthUnit::FootSurvey => Length::new::<foot_survey>(value),
            LengthUnit::Gigameter => Length::new::<gigameter>(value),
            LengthUnit::Hectometer => Length::new::<hectometer>(value),
            LengthUnit::Inch => Length::new::<inch>(value),
            LengthUnit::Kilometer => Length::new::<kilometer>(value),
            LengthUnit::LightYear => Length::new::<light_year>(value),
            LengthUnit::Megameter => Length::new::<megameter>(value),
            LengthUnit::Meter => Length::new::<meter>(value),
            LengthUnit::Microinch => Length::new::<microinch>(value),
            LengthUnit::Micrometer => Length::new::<micrometer>(value),
            LengthUnit::Micron => Length::new::<micron>(value),
            LengthUnit::Mil => Length::new::<mil>(value),
            LengthUnit::Mile => Length::new::<mile>(value),
            LengthUnit::MileSurvey => Length::new::<mile_survey>(value),
            LengthUnit::Millimeter => Length::new::<millimeter>(value),
            LengthUnit::Nanometer => Length::new::<nanometer>(value),
            LengthUnit::NauticalMile => Length::new::<nautical_mile>(value),
            LengthUnit::Parsec => Length::new::<parsec>(value),
            LengthUnit::Petameter => Length::new::<petameter>(value),
            LengthUnit::PicaComputer => Length::new::<pica_computer>(value),
            LengthUnit::PicaPrinters => Length::new::<pica_printers>(value),
            LengthUnit::Picometer => Length::new::<picometer>(value),
            LengthUnit::PointComputer => Length::new::<point_computer>(value),
            LengthUnit::PointPrinters => Length::new::<point_printers>(value),
            LengthUnit::Rod => Length::new::<rod>(value),
            LengthUnit::Terameter => Length::new::<terameter>(value),
            LengthUnit::Yard => Length::new::<yard>(value),
            LengthUnit::Yoctometer => Length::new::<yoctometer>(value),
            LengthUnit::Yottameter => Length::new::<yottameter>(value),
            LengthUnit::Zeptometer => Length::new::<zeptometer>(value),
            LengthUnit::Zettameter => Length::new::<zettameter>(value),
        }
    }

    fn get(&self, length: Length) -> f32 {
        match self {
            LengthUnit::Angstrom => length.get::<angstrom>(),
            LengthUnit::AstronomicalUnit => length.get::<astronomical_unit>(),
            LengthUnit::AtomicUnitOfLength => length.get::<atomic_unit_of_length>(),
            LengthUnit::Attometer => length.get::<attometer>(),
            LengthUnit::BohrRadius => length.get::<bohr_radius>(),
            LengthUnit::Centimeter => length.get::<centimeter>(),
            LengthUnit::Chain => length.get::<chain>(),
            LengthUnit::Decameter => length.get::<decameter>(),
            LengthUnit::Decimeter => length.get::<decimeter>(),
            LengthUnit::Exameter => length.get::<exameter>(),
            LengthUnit::Fathom => length.get::<fathom>(),
            LengthUnit::Femtometer => length.get::<femtometer>(),
            LengthUnit::Fermi => length.get::<fermi>(),
            LengthUnit::Foot => length.get::<foot>(),
            LengthUnit::FootSurvey => length.get::<foot_survey>(),
            LengthUnit::Gigameter => length.get::<gigameter>(),
            LengthUnit::Hectometer => length.get::<hectometer>(),
            LengthUnit::Inch => length.get::<inch>(),
            LengthUnit::Kilometer => length.get::<kilometer>(),
            LengthUnit::LightYear => length.get::<light_year>(),
            LengthUnit::Megameter => length.get::<megameter>(),
            LengthUnit::Meter => length.get::<meter>(),
            LengthUnit::Microinch => length.get::<microinch>(),
            LengthUnit::Micrometer => length.get::<micrometer>(),
            LengthUnit::Micron => length.get::<micron>(),
            LengthUnit::Mil => length.get::<mil>(),
            LengthUnit::Mile => length.get::<mile>(),
            LengthUnit::MileSurvey => length.get::<mile_survey>(),
            LengthUnit::Millimeter => length.get::<millimeter>(),
            LengthUnit::Nanometer => length.get::<nanometer>(),
            LengthUnit::NauticalMile => length.get::<nautical_mile>(),
            LengthUnit::Parsec => length.get::<parsec>(),
            LengthUnit::Petameter => length.get::<petameter>(),
            LengthUnit::PicaComputer => length.get::<pica_computer>(),
            LengthUnit::PicaPrinters => length.get::<pica_printers>(),
            LengthUnit::Picometer => length.get::<picometer>(),
            LengthUnit::PointComputer => length.get::<point_computer>(),
            LengthUnit::PointPrinters => length.get::<point_printers>(),
            LengthUnit::Rod => length.get::<rod>(),
            LengthUnit::Terameter => length.get::<terameter>(),
            LengthUnit::Yard => length.get::<yard>(),
            LengthUnit::Yoctometer => length.get::<yoctometer>(),
            LengthUnit::Yottameter => length.get::<yottameter>(),
            LengthUnit::Zeptometer => length.get::<zeptometer>(),
            LengthUnit::Zettameter => length.get::<zettameter>(),
        }
    }

    fn name(&self) -> &'static str {
        match self {
            LengthUnit::Angstrom => "Å",
            LengthUnit::AstronomicalUnit => "au",
            LengthUnit::AtomicUnitOfLength => "a₀",
            LengthUnit::Attometer => "am",
            LengthUnit::BohrRadius => "bohr",
            LengthUnit::Centimeter => "cm",
            LengthUnit::Chain => "ch",
            LengthUnit::Decameter => "dam",
            LengthUnit::Decimeter => "dm",
            LengthUnit::Exameter => "Em",
            LengthUnit::Fathom => "ftm",
            LengthUnit::Femtometer => "fm",
            LengthUnit::Fermi => "fermi",
            LengthUnit::Foot => "ft",
            LengthUnit::FootSurvey => "ft (US survey)",
            LengthUnit::Gigameter => "Gm",
            LengthUnit::Hectometer => "hm",
            LengthUnit::Inch => "in",
            LengthUnit::Kilometer => "km",
            LengthUnit::LightYear => "ly",
            LengthUnit::Megameter => "Mm",
            LengthUnit::Meter => "m",
            LengthUnit::Microinch => "μin",
            LengthUnit::Micrometer => "μm",
            LengthUnit::Micron => "micron",
            LengthUnit::Mil => "mil",
            LengthUnit::Mile => "mi",
            LengthUnit::MileSurvey => "mi (US survey)",
            LengthUnit::Millimeter => "mm",
            LengthUnit::Nanometer => "nm",
            LengthUnit::NauticalMile => "nmi",
            LengthUnit::Parsec => "pc",
            LengthUnit::Petameter => "Pm",
            LengthUnit::PicaComputer => "pica (comp)",
            LengthUnit::PicaPrinters => "pica (print)",
            LengthUnit::Picometer => "pm",
            LengthUnit::PointComputer => "pt (comp)",
            LengthUnit::PointPrinters => "pt (print)",
            LengthUnit::Rod => "rd",
            LengthUnit::Terameter => "Tm",
            LengthUnit::Yard => "yd",
            LengthUnit::Yoctometer => "ym",
            LengthUnit::Yottameter => "Ym",
            LengthUnit::Zeptometer => "zm",
            LengthUnit::Zettameter => "Zm",
        }
    }
}

#[derive(Clone, Copy)]
enum MassUnit {
    Attogram,
    Femtogram,
    Picogram,
    Nanogram,
    Microgram,
    Milligram,
    Centigram,
    Decigram,
    Gram,
    Decagram,
    Hectogram,
    Kilogram,
    Megagram,
    Gigagram,
    Teragram,
    Petagram,
    Exagram,
    Zettagram,
    Yottagram,
    Yoctogram,
    Zeptogram,
    Dalton,
    Carat,
    Grain,
    HundredweightLong,
    HundredweightShort,
    Tonne,
    Ton,
    TonAssay,
    TonLong,
    TonShort,
    Ounce,
    OunceTroy,
    Pennyweight,
    Pound,
    PoundTroy,
    Slug,
    Stone,
}

impl MassUnit {
    fn create(&self, value: f32) -> Mass {
        match self {
            MassUnit::Attogram => Mass::new::<attogram>(value),
            MassUnit::Femtogram => Mass::new::<femtogram>(value),
            MassUnit::Picogram => Mass::new::<picogram>(value),
            MassUnit::Nanogram => Mass::new::<nanogram>(value),
            MassUnit::Microgram => Mass::new::<microgram>(value),
            MassUnit::Milligram => Mass::new::<milligram>(value),
            MassUnit::Centigram => Mass::new::<centigram>(value),
            MassUnit::Decigram => Mass::new::<decigram>(value),
            MassUnit::Gram => Mass::new::<gram>(value),
            MassUnit::Decagram => Mass::new::<decagram>(value),
            MassUnit::Hectogram => Mass::new::<hectogram>(value),
            MassUnit::Kilogram => Mass::new::<kilogram>(value),
            MassUnit::Megagram => Mass::new::<megagram>(value),
            MassUnit::Gigagram => Mass::new::<gigagram>(value),
            MassUnit::Teragram => Mass::new::<teragram>(value),
            MassUnit::Petagram => Mass::new::<petagram>(value),
            MassUnit::Exagram => Mass::new::<exagram>(value),
            MassUnit::Zettagram => Mass::new::<zettagram>(value),
            MassUnit::Yottagram => Mass::new::<yottagram>(value),
            MassUnit::Yoctogram => Mass::new::<yoctogram>(value),
            MassUnit::Zeptogram => Mass::new::<zeptogram>(value),
            MassUnit::Dalton => Mass::new::<dalton>(value),
            MassUnit::Carat => Mass::new::<carat>(value),
            MassUnit::Grain => Mass::new::<grain>(value),
            MassUnit::HundredweightLong => Mass::new::<hundredweight_long>(value),
            MassUnit::HundredweightShort => Mass::new::<hundredweight_short>(value),
            MassUnit::Tonne => Mass::new::<tonne>(value),
            MassUnit::Ton => Mass::new::<ton>(value),
            MassUnit::TonAssay => Mass::new::<ton_assay>(value),
            MassUnit::TonLong => Mass::new::<ton_long>(value),
            MassUnit::TonShort => Mass::new::<ton_short>(value),
            MassUnit::Ounce => Mass::new::<ounce>(value),
            MassUnit::OunceTroy => Mass::new::<ounce_troy>(value),
            MassUnit::Pennyweight => Mass::new::<pennyweight>(value),
            MassUnit::Pound => Mass::new::<pound>(value),
            MassUnit::PoundTroy => Mass::new::<pound_troy>(value),
            MassUnit::Slug => Mass::new::<slug>(value),
            MassUnit::Stone => Mass::new::<stone>(value),
        }
    }

    fn get(&self, mass: Mass) -> f32 {
        match self {
            MassUnit::Attogram => mass.get::<attogram>(),
            MassUnit::Femtogram => mass.get::<femtogram>(),
            MassUnit::Picogram => mass.get::<picogram>(),
            MassUnit::Nanogram => mass.get::<nanogram>(),
            MassUnit::Microgram => mass.get::<microgram>(),
            MassUnit::Milligram => mass.get::<milligram>(),
            MassUnit::Centigram => mass.get::<centigram>(),
            MassUnit::Decigram => mass.get::<decigram>(),
            MassUnit::Gram => mass.get::<gram>(),
            MassUnit::Decagram => mass.get::<decagram>(),
            MassUnit::Hectogram => mass.get::<hectogram>(),
            MassUnit::Kilogram => mass.get::<kilogram>(),
            MassUnit::Megagram => mass.get::<megagram>(),
            MassUnit::Gigagram => mass.get::<gigagram>(),
            MassUnit::Teragram => mass.get::<teragram>(),
            MassUnit::Petagram => mass.get::<petagram>(),
            MassUnit::Exagram => mass.get::<exagram>(),
            MassUnit::Zettagram => mass.get::<zettagram>(),
            MassUnit::Yottagram => mass.get::<yottagram>(),
            MassUnit::Yoctogram => mass.get::<yoctogram>(),
            MassUnit::Zeptogram => mass.get::<zeptogram>(),
            MassUnit::Dalton => mass.get::<dalton>(),
            MassUnit::Carat => mass.get::<carat>(),
            MassUnit::Grain => mass.get::<grain>(),
            MassUnit::HundredweightLong => mass.get::<hundredweight_long>(),
            MassUnit::HundredweightShort => mass.get::<hundredweight_short>(),
            MassUnit::Tonne => mass.get::<tonne>(),
            MassUnit::Ton => mass.get::<ton>(),
            MassUnit::TonAssay => mass.get::<ton_assay>(),
            MassUnit::TonLong => mass.get::<ton_long>(),
            MassUnit::TonShort => mass.get::<ton_short>(),
            MassUnit::Ounce => mass.get::<ounce>(),
            MassUnit::OunceTroy => mass.get::<ounce_troy>(),
            MassUnit::Pennyweight => mass.get::<pennyweight>(),
            MassUnit::Pound => mass.get::<pound>(),
            MassUnit::PoundTroy => mass.get::<pound_troy>(),
            MassUnit::Slug => mass.get::<slug>(),
            MassUnit::Stone => mass.get::<stone>(),
        }
    }
}
